BIT/Other/IIS-Filip/members/urls.py
from django.conf.urls import patterns, url
from members import views

urlpatterns = patterns(
    '',
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^change_password/$', views.user_change_password, name='change_password'),
    url(r'^members/$', views.members, name='members'),
    url(r'^members/(?P<username>\w+)/$', views.change_member, name='change_member'),
    url(r'^reset_password/(?P<username>\w+)/$', views.reset_password, name='reset_password'),
    url(r'^add_member/$', views.add_member, name='add_member'),
    url(r'^delete_members/$', views.delete_members, name='delete_members'),
)

BIT/Other/IIS-Filip/pekarna/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^$', login_required(TemplateView.as_view(template_name='base.html'))),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^shopping/', include('shopping.urls')),
    url(r'^shipping/', include('shipping.urls')),
    url(r'^members/', include('members.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

BIT/Other/IIS-Filip/shopping/urls.py
from django.conf.urls import patterns, url
from shopping import views

urlpatterns = patterns(
    '',
    url(r'^ingredients/$', views.ingredients, name='ingredients'),
    url(r'^ingredients/(?P<id>\d+)/$', views.change_ingredient, name='change_ingredient'),
    url(r'^add_ingredient/$', views.add_ingredient, name='add_ingredient'),
    url(r'^pastries/$', views.pastries, name='pastries'),
    url(r'^pastries/(?P<id>\d+)/$', views.change_pastry, name='change_pastry'),
    url(r'^add_pastry/$', views.add_pastry, name='add_pastry'),
    url(r'^orders/$', views.orders, name='orders'),
    url(r'^orders/(?P<id>\d+)/$', views.change_order, name='change_order'),
    url(r'^complete_order/(?P<id>\d+)/$', views.complete_order, name='complete_order'),
    url(r'^change_arrival_date/(?P<id>\d+)/$', views.change_arrival_date, name='change_arrival_date'),
    url(r'^pay_order/(?P<id>\d+)/$', views.pay_order, name='pay_order'),
    url(r'^add_order/$', views.add_order, name='add_order'),
    url(r'^delete_orders/$', views.delete_orders, name='delete_orders'),
    url(r'^delete_pastries/$', views.delete_pastries, name='delete_pastries'),
    url(r'^delete_ingredients/$', views.delete_ingredients, name='delete_ingredients'),
)

BIT/Other/IIS-Filip/shopping/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.validators import MinValueValidator
from shipping.models import DeliveryAddress
from members.models import Customer


class Ingredient(models.Model):
    name = models.CharField(_("Name"), max_length=50, db_index=True, unique=True)
    purchase_price = models.FloatField(_("Purchase price"), validators=[MinValueValidator(0)])
    amount = models.FloatField(_("Amount in kg"))

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = _("Ingredient")
        verbose_name_plural = _("Ingredients")


class Pastry(models.Model):
    name = models.CharField(_("Name"), max_length=50, db_index=True, unique=True)
    price = models.FloatField(_("Price"), validators=[MinValueValidator(0)])
    allergens = models.CharField(_("Allergens"), max_length=150, blank=True)
    units_per_batch = models.PositiveIntegerField(_("Units per batch"), validators=[MinValueValidator(1)])
    ingredients = models.ManyToManyField(Ingredient, through='IngredientNeedRelation')

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = _("Ingredient")
        verbose_name_plural = _("Ingredients")


class IngredientNeedRelation(models.Model):
    pastry = models.ForeignKey(Pastry)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.PROTECT)
    amount = models.FloatField(_("Amount in kg"), validators=[MinValueValidator(1)])

    class Meta:
        unique_together = ['pastry', 'ingredient']


class Order(models.Model):
    IN_PERSON = "P"
    IN_STORE = "S"
    DELIVERY_METHOD = (
        (IN_PERSON, _("Personally")),
        (IN_STORE, _("In the store"))
    )

    DELIVERY_CASH = "D"
    CREDIT_CARD = "C"
    BANK_TRANSFER = "T"
    PAYMENT_METHOD = (
        (DELIVERY_CASH, _("Cash on delivery")),
        (CREDIT_CARD, _("Credit card")),
        (BANK_TRANSFER, _("Bank transfer"))
    )

    arrival_date = models.DateField(_("Arrival date"), null=True, blank=True)
    completed_date = models.DateField(_("Date completed"), null=True, blank=True)
    order_date = models.DateField(_("Order date"), auto_now_add=True)
    delivery_method = models.CharField(_("Delivery method"), max_length=1, choices=DELIVERY_METHOD, default=IN_PERSON)
    payment_method = models.CharField(_("Payment method"), max_length=1, choices=PAYMENT_METHOD, default=DELIVERY_CASH)
    delivery_address = models.ForeignKey(DeliveryAddress, verbose_name=_("Delivery address"), on_delete=models.PROTECT)
    customer = models.ForeignKey(Customer, verbose_name=_("Customer"), on_delete=models.PROTECT)
    paid = models.BooleanField(_("Is paid"), default=False)
    completed = models.BooleanField(_("Is completed"), default=False)
    price = models.FloatField(_("Order price"), validators=[MinValueValidator(0)])
    items = models.ManyToManyField(Pastry, through='OrderItemRelation')

    def __unicode__(self):
        return unicode(_("Order n.")) + str(self.id)

    class Meta:
        verbose_name = _("Order")
        verbose_name_plural = _("Orders")

    def get_delivery_method(self):
        return dict(self.DELIVERY_METHOD)[self.delivery_method]

    def get_payment_method(self):
        return dict(self.PAYMENT_METHOD)[self.payment_method]


class OrderItemRelation(models.Model):
    order = models.ForeignKey(Order)
    pastry = models.ForeignKey(Pastry, on_delete=models.PROTECT)
    amount = models.PositiveSmallIntegerField(_("Amount"), validators=[MinValueValidator(1)])

BIT/Other/IIS-Filip/shopping/views.py
from django.shortcuts import get_object_or_404
from .models import Ingredient, Pastry, IngredientNeedRelation, Order, OrderItemRelation
from .forms import IngredientForm, PastryForm, OrderForm, OrderArrivalDateForm
from pekarna.abstract_views import AbstractView, ManageAbstractView, is_popup
from django.forms.models import inlineformset_factory
from django.db.models import Count, Sum
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseForbidden
from django.core.urlresolvers import reverse
from django import forms
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils.translation import ugettext_lazy as _
from django.db import transaction
from collections import defaultdict
from datetime import datetime
from shopping.models import DeliveryAddress


@login_required
def ingredients(request):
    if request.user.is_manager() or request.user.is_admin() or is_popup(request):
        ingredientView = IngredientView(request)
        return ingredientView.render()
    return HttpResponseForbidden()


@login_required
def add_ingredient(request):
    if request.user.is_manager() or request.user.is_admin():
        addIngredientView = AddIngredientView(request)
        return addIngredientView.render()
    return HttpResponseForbidden()


@login_required
def change_ingredient(request, id):
    if request.user.is_manager() or request.user.is_admin():
        ingredient = get_object_or_404(Ingredient, id=id)

        changeIngredientView = ChangeIngredientView(request, ingredient)
        return changeIngredientView.render()
    return HttpResponseForbidden()


class IngredientView(AbstractView):

    def get_queryset(self):
        return Ingredient.objects.all()

    def get_search_list(self):
        return ["name"]

    def get_template(self):
        return "shopping/ingredients.html"


class AddIngredientView(ManageAbstractView):

    def get_form(self):
        return IngredientForm

    def get_template(self):
        return "shopping/add_ingredient.html"

    def get_reverse_url(self):
        return "ingredients"


class ChangeIngredientView(AddIngredientView):
    def get_template(self):
        return "shopping/change_ingredient.html"


@login_required
def pastries(request):
    ingredientView = PastryView(request)
    return ingredientView.render()


@login_required
def add_pastry(request):
    if request.user.is_admin() or request.user.is_manager():
        addPastryView = AddPastryView(request)
        return addPastryView.render()
    return HttpResponseForbidden()


@login_required
def change_pastry(request, id):
    pastry = get_object_or_404(Pastry, id=id)

    changePastryView = ChangePastryView(request, pastry)
    return changePastryView.render()


class PastryView(AbstractView):

    def get_queryset(self):
        return Pastry.objects.annotate(Count('ingredients')).all()

    def get_search_list(self):
        return ["name", "allergens"]

    def get_template(self):
        return "shopping/pastries.html"


class AddPastryView(ManageAbstractView):

    def get_form(self):
        return PastryForm

    def get_template(self):
        return "shopping/add_pastry.html"

    def get_reverse_url(self):
        return "pastries"

    def get_formset(self):
        return inlineformset_factory(
            Pastry, Pastry.ingredients.through,
            fields=("ingredient", "amount",),
            widgets={
                "ingredient": forms.TextInput(attrs={
                    "class": "mdl-textfield__input fk"
                }),
                "amount": forms.TextInput(attrs={
                    "class": "mdl-textfield__input amount",
                }),
            },
            extra=0,
            min_num=1,
            validate_min=True,
            can_delete=True)


class ChangePastryView(AddPastryView):
    def get_template(self):
        return "shopping/change_pastry.html"


@login_required
def orders(request):
    ingredientView = OrderView(request)
    return ingredientView.render()


@login_required
def add_order(request):
    if not request.user.is_driver():
        addOrderView = AddOrderGeneralView(request)
        return addOrderView.render()
    return HttpResponseForbidden()


@login_required
def change_order(request, id):
    order = get_object_or_404(Order, id=id)

    if request.user.is_customer() and order.customer != request.user.customer_set:
        return HttpResponseForbidden()

    if request.user.is_customer():
        allowed_orders = Order.objects.filter(customer=request.user.customer_set)

        if order not in allowed_orders:
            return HttpResponseForbidden()

    elif request.user.is_driver():
        driver = request.user.driver_set
        distribution_areas = driver.distributionarea_set.all()
        delivery_addresses = DeliveryAddress.objects.filter(distribution_area__in=distribution_areas)
        allowed_orders = Order.objects.filter(delivery_address=delivery_addresses, completed=False, paid=True)

        if order not in allowed_orders:
            return HttpResponseForbidden()

    changeOrderView = ChangeOrderView(request, order)
    return changeOrderView.render()


@login_required
def delete_orders(request):
    if request.user.is_manager() or request.user.is_admin() or request.user.is_customer():
        obj_ids = request.POST.get("obj_ids")

        if obj_ids == '' or obj_ids is None:
            msg = _("No object was selected!")
            messages.add_message(request, messages.INFO, msg)
            return HttpResponseRedirect("/shopping/orders/")

        obj_ids = obj_ids.split(",")
        objects = Order.objects.filter(id__in=obj_ids)

        try:
            if objects.filter(paid=True).exists():
                raise BaseException()
            objects.delete()
            msg = _("Selected orders were deleted!")
        except:
            msg = _("Some orders could not be deleted!")
        messages.add_message(request, messages.INFO, msg)

        return HttpResponseRedirect("/shopping/orders/")
    return HttpResponseForbidden()


@login_required
def delete_pastries(request):
    if request.user.is_admin() or request.user.is_manager():
        obj_ids = request.POST.get("obj_ids")

        if obj_ids == '' or obj_ids is None:
            msg = _("No object was selected!")
            messages.add_message(request, messages.INFO, msg)
            return HttpResponseRedirect("/shopping/pastries/")

        obj_ids = obj_ids.split(",")
        objects = Pastry.objects.filter(id__in=obj_ids)

        try:
            objects.delete()
            msg = _("Selected pastries were deleted!")
        except:
            msg = _("Some pastries could not be deleted!")
        messages.add_message(request, messages.INFO, msg)

        return HttpResponseRedirect("/shopping/pastries/")
    return HttpResponseForbidden()


@login_required
def delete_ingredients(request):
    if request.user.is_admin() or request.user.is_manager():
        obj_ids = request.POST.get("obj_ids")

        if obj_ids == '' or obj_ids is None:
            msg = _("No object was selected!")
            messages.add_message(request, messages.INFO, msg)
            return HttpResponseRedirect("/shopping/ingredients/")

        obj_ids = obj_ids.split(",")
        objects = Ingredient.objects.filter(id__in=obj_ids)

        try:
            objects.delete()
            msg = _("Selected ingredients were deleted!")
        except:
            msg = _("Some ingredients could not be deleted!")
        messages.add_message(request, messages.INFO, msg)

        return HttpResponseRedirect("/shopping/ingredients/")
    return HttpResponseForbidden()


class OrderView(AbstractView):

    def delete(self):
        return True

    def get_queryset(self):
        if self.request.user.is_customer():
            return Order.objects.filter(customer=self.request.user.customer_set)
        elif self.request.user.is_driver():
            driver = self.request.user.driver_set
            distribution_areas = driver.distributionarea_set.all()
            delivery_addresses = DeliveryAddress.objects.filter(distribution_area__in=distribution_areas)

            return Order.objects.filter(delivery_address=delivery_addresses, completed=False, paid=True)
        else:
            return Order.objects.all()

    def get_search_list(self):
        return ["customer__person__last_name", "customer__person__first_name",
                "delivery_address__city", "delivery_address__street",
                "delivery_address__house_number", "id"]

    def get_template(self):
        return "shopping/orders.html"


class AddOrderGeneralView(ManageAbstractView):

    def get_form(self):
        return OrderForm

    def get_template(self):
        return "shopping/add_order.html"

    def get_reverse_url(self):
        return "orders"

    def get_formset(self):
        return inlineformset_factory(
            Order, Order.items.through,
            fields=("pastry", "amount",),
            widgets={
                "pastry": forms.TextInput(attrs={
                    "class": "mdl-textfield__input fk"
                }),
                "amount": forms.TextInput(attrs={
                    "class": "mdl-textfield__input amount",
                }),
            },
            extra=0,
            min_num=1,
            validate_min=True,
            can_delete=True)

    def calculate_pastry_sum(self, cleaned_data):
        sum_price = 0

        for obj in cleaned_data:
            if any(obj) is False or obj["DELETE"] == True:
                # Check if dictionary is empty
                continue

            pastry_price = int(obj["pastry"].price)
            amount = int(obj["amount"])
            sum_price += pastry_price * amount

        return sum_price

    def render(self):
        form = None
        formset = None

        if self.request.method == "POST":

BIT/Other/IIS-Filip/templates/shopping/add_ingredient.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block title %}Ingrediencie{% endblock %}

{% block header_title %}Manažovanie ingrediencií{% endblock header_title %}

{% block page_title %}Ingrediencie{% endblock page_title %}

{% block tabview %}
<div class="mdl-layout__header-row nav_tab">
    <a href="{% url 'ingredients' %}" class="mdl-layout__tab">{% trans 'Change' %}</a>
    <a href="{% url 'add_ingredient' %}" class="mdl-layout__tab is-active">{% trans 'Add' %}</a>
</div>
{% endblock tabview %}

{% block content %}
  <div class="card404-wide-ingredient-form mdl-card mdl-shadow--4dp mdl-cell mdl-cell--8-col">
    <div class="mdl-card__title">
      <h2 class="mdl-card__title-text">Pridanie novej ingrediencie</h2>
    </div>
    <form class="form-horizontal" action="" method="POST" {% if form.is_multipart %}enctype="multipart/form-data"{% endif %}>
      <div class="mdl-card__supporting-text">
        {% csrf_token %}
        {{ form.media }}
        {% if form.errors %}
          <ul>
            {% for error in form.non_field_errors %}
              <li>{{ error }}</li>
            {% endfor %}
          </ul>
        {% endif %}

        {% for field in form.visible_fields %}
        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
          {{ field }}
          <label class="mdl-textfield__label">{{ field.label }}</label>
        </div>
        <span>{% if field.errors %}{{ field.errors.as_text }}{% endif %}</span>
        <br>
        {% endfor %}

        {% for field in form.hidden_fields %}
            {{ field }}
        {% endfor %}

        <div class="mdl-card__actions  mdl-card--border">
          <input class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" type="submit" value="{% trans 'Submit' %}"/>
        </div>
      </div>
    </form>
  </div>
{% endblock content %}

BIT/Other/IIS-Filip/templates/shopping/add_order.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block title %}{% trans 'Orders' %}{% endblock %}

{% block header_title %}Manažovanie objednávok{% endblock header_title %}

{% block page_title %}Vytváranie {% trans 'Orders' %}{% endblock page_title %}

{% block tabview %}
<div class="mdl-layout__header-row nav_tab">
    <a href="{% url 'orders' %}" class="mdl-layout__tab">{% trans 'Change' %}</a>
    <a href="{% url 'add_order' %}" class="mdl-layout__tab is-active">{% trans 'Add' %}</a>
</div>
{% endblock tabview %}

{% block content %}
  <div class="card404-wide-order-form mdl-card mdl-shadow--4dp mdl-cell mdl-cell--12-col">
    <div class="mdl-card__title">
      <h2 class="mdl-card__title-text">Vytvorenie novej {% trans 'Orders' %}</h2>
    </div>
    <form class="form-horizontal" action="" method="POST" {% if form.is_multipart %}enctype="multipart/form-data"{% endif %}>
      <div class="mdl-card__supporting-text">
        {% csrf_token %}
        {{ form.media }}
        {% if form.errors %}
          <ul>
            {% for error in form.non_field_errors %}
              <li>{{ error }}</li>
            {% endfor %}
          </ul>
        {% endif %}

        {% for field in form.visible_fields %}
          {% if field.id_for_label == form.paid.id_for_label %}
            {% if not user.is_customer %}
            <label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" for="id_paid">
              <input type="checkbox" id="id_paid" name="paid" class="mdl-checkbox__input"{%if field.value %} checked{%endif%}/>
              <span class="mdl-checkbox__label">{{ field.label }}</span>
            </label>
            <br><br>
            {% endif %}
          {% elif field.id_for_label == form.completed.id_for_label %}
          {% elif field.id_for_label == form.completed_date.id_for_label %}
          {% elif field.id_for_label == form.arrival_date.id_for_label %}
            {% if not user.is_customer %}
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
              {{ field }}
              <label class="mdl-textfield__label">{{field.label}}</label>
            </div>
            <br>
            {% endif %}
          {% elif field.id_for_label == form.completed_date.id_for_label %}
          {% elif field.id_for_label == form.customer.id_for_label%}
            {% if not user.is_customer %}
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
              {{ field }}
              <label class="mdl-textfield__label">{{ field.label }}</label>
              <input class="mdl-textfield__input fk_content" type="text" value="{{form.instance.customer|default_if_none:_("None")}}" readonly>
              <a href="{% url 'members'%}?popup=customers" name="Customer" class="fk_lookup"><i class="material-icons">search</i></a>
            </div>
            <br>
            {% endif %}
          {% elif field.id_for_label == form.price.id_for_label %}
          {% else %}
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
              {{ field }}
              <label class="mdl-textfield__label">{{ field.label }}</label>
              {% if field.id_for_label == form.delivery_address.id_for_label %}
              <input class="mdl-textfield__input fk_content" type="text" value="{{form.instance.delivery_address|default_if_none:"Žiadna"}}" readonly>
              <a href="{% url 'delivery_addresses'%}?popup=1" name="Delivery Address" class="fk_lookup"><i class="material-icons">search</i></a>
              {% endif %}
            </div>
            <span>{% if field.errors %}{{ field.errors.as_text }}{% endif %}</span>
            <br>
          {% endif %}
        {% endfor %}

        {% for field in form.hidden_fields %}
            {{ field }}
        {% endfor %}

        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label is-dirty is-upgraded" data-upgraded=",MaterialTextfield">
          <input class="mdl-textfield__input" id="id_sum_price" value="NaN" readonly>
          <label class="mdl-textfield__label">{% trans 'Price' %}</label>
        </div>

        <br>

        {{ formset.management_form }}
        <div class="table-wrapper mdl-grid mdl-cell--2-col-phone">
        <table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp">
          <thead>
            <tr>
              <th class="mdl-data-table__cell--non-numeric fk_th">{% trans 'Pastry' %}</th>
              <th class="mdl-data-table__cell--non-numeric">Počet kusov</th>
              <th>{% trans 'Delete' %}</th>
            </tr>
          </thead>
          <tbody>
            {% for form in formset.forms %}
              <tr class="dynamic-form">
              {% for field in form.visible_fields %}
                <td>
                {{ field }}
                {% if field.id_for_label == form.pastry.id_for_label %}
                <input class="mdl-textfield__input fk_content" type="text" value="{{form.instance.pastry|default_if_none:'Žiadny'}}" readonly>
                <input class="mdl-textfield__input price" type="text" value="{{form.instance.pastry.price}}" readonly>
                <a href="{% url 'pastries'%}?popup=1" name="Pastry" class="fk_lookup"><i class="material-icons">search</i></a>
                {% endif %}
                {% if field.errors %}<span class="error_span">{{ field.errors.as_text }}</span>{% endif %}
                </td>
              {% endfor %}
              </tr>

              {% for field in form.hidden_fields %}
                {{ field }}
              {% endfor %}
            {% endfor %} 
          </tbody>
        </table>
        </div>

        <br><br>

        <div class="mdl-card__actions  mdl-card--border">
          <input class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" type="submit" value="{% trans 'Submit' %}"/>
        </div>
      </div>
    </form>
  </div>
{% endblock content %}

{% block optional_js %}
<script type="text/javascript" src="{% static 'js/jquery_formset.js' %}"></script>
<script type="text/javascript" src="{% static 'js/order_form.js' %}"></script>
<script type="text/javascript">
    $(function() {
        $('form tbody tr').formset({
            prefix: '{{ formset.prefix }}',
            addText: 'Pridať ďalšie',
            deleteText: 'Odstrániť',
        });
    })
</script>
{% endblock %}

BIT/Other/IIS-Filip/templates/shopping/add_pastry.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block title %}{% trans 'Pastry' %}{% endblock %}

{% block header_title %}{% trans 'Manage pastry' %}{% endblock header_title %}

{% block page_title %}{% trans 'Add pastry' %}{% endblock page_title %}

{% block tabview %}
<div class="mdl-layout__header-row nav_tab">
    <a href="{% url 'pastries' %}" class="mdl-layout__tab">{% trans 'Change' %}</a>
    <a href="{% url 'add_pastry' %}" class="mdl-layout__tab is-active">{% trans 'Add' %}</a>
</div>
{% endblock tabview %}

{% block content %}
  <div class="card404-wide-bread-form mdl-card mdl-shadow--4dp mdl-cell mdl-cell--12-col">
    <div class="mdl-card__title">
      <h2 class="mdl-card__title-text">Pridanie nového pečiva</h2>
    </div>
    <form class="form-horizontal" action="" method="POST" {% if form.is_multipart %}enctype="multipart/form-data"{% endif %}>
      <div class="mdl-card__supporting-text">
        {% csrf_token %}
        {{ form.media }}
        {% if form.errors %}
          <ul>
            {% for error in form.non_field_errors %}
              <li>{{ error }}</li>
            {% endfor %}
          </ul>
        {% endif %}

        {% for field in form.visible_fields %}
        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
          {{ field }}
          <label class="mdl-textfield__label">{{ field.label }}</label>
        </div>
        <span>{% if field.errors %}{{ field.errors.as_text }}{% endif %}</span>
        <br>
        {% endfor %}

        {% for field in form.hidden_fields %}
            {{ field }}
        {% endfor %}

        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label is-dirty is-upgraded" data-upgraded=",MaterialTextfield">
          <input class="mdl-textfield__input" id="id_sum_price" name="sum_price" value="NaN" readonly>
          <label class="mdl-textfield__label">{% trans 'Ingredients price' %}</label>
        </div>

        <br>

        {{ formset.management_form }}
        <div class="table-wrapper mdl-grid mdl-cell--2-col-phone">
          <table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp">
            <thead>
              <tr>
                <th class="mdl-data-table__cell--non-numeric fk_th">{% trans 'Ingredient' %}</th>
                <th class="mdl-data-table__cell--non-numeric">{% trans 'Amount in KG' %}</th>
                <th>{% trans 'Delete' %}</th>
              </tr>
            </thead>
            <tbody>
              {% for form in formset.forms %}
                <tr class="dynamic-form">
                {% for field in form.visible_fields %}
                  <td>
                  {{ field }}
                  {% if field.id_for_label == form.ingredient.id_for_label %}
                  <input class="mdl-textfield__input fk_content" type="text" value="{{form.instance.ingredient|default_if_none:'Žiadny'}}" readonly>
                  <input class="mdl-textfield__input price" type="text" value="{{form.instance.ingredient.purchase_price}}" readonly>
                  <a href="{% url 'ingredients'%}?popup=1" class="fk_lookup"><i class="material-icons">search</i></a>
                  {% endif %}
                  {% if field.errors %}<span class="error_span">{{ field.errors.as_text }}</span>{% endif %}
                  </td>
                {% endfor %}
                </tr>

                {% for field in form.hidden_fields %}
                  {{ field }}
                {% endfor %}
              {% endfor %} 
            </tbody>
          </table>
        </div>

        <br><br>

        <div class="mdl-card__actions  mdl-card--border">
          <input class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" type="submit" value="{% trans 'Submit' %}"/>
        </div>
      </div>
    </form>
  </div>
{% endblock content %}

{% block optional_js %}
<script type="text/javascript" src="{% static 'js/jquery_formset.js' %}"></script>
<script type="text/javascript" src="{% static 'js/pastry_form.js' %}"></script>
<script type="text/javascript">
    $(function() {
        $('form tbody tr').formset({
            prefix: '{{ formset.prefix }}',
            addText: 'Pridať ďalšie',
            deleteText: 'Odstrániť',
        });
    })
</script>
{% endblock %}